// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://razcrnqmuqnjzuvyasen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhemNybnFtdXFuanp1dnlhc2VuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODY2OTgsImV4cCI6MjA3MjY2MjY5OH0.zFbZMhBL1PFELu4ztbquxfUxU2bs7-RZa5HD-0VDbKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});